package com.example.mobile.domain

enum class AchievementProgressSource {
    HABIT_COUNT,
    CURRENT_STREAK,
    TOTAL_COMPLETIONS,
    TOTAL_XP,
    PET_LEVEL,
    OWNED_CUSTOMIZATIONS,
    BEST_STREAK,
    BEST_COMBO,
    DAYS_ACTIVE,
    PET_AGE_DAYS,
    TOTAL_COINS,
    FREEZES_USED,
    CHALLENGES_COMPLETED,
    CHESTS_OPENED,
    DAILY_LOGINS,
    EVOLUTIONS,
    ACHIEVEMENTS_CLAIMED,
    TITLES_UNLOCKED,
    FRAMES_UNLOCKED,
    SETS_COMPLETED
}
