package com.example.mobile.navigation

import androidx.compose.animation.core.animateDpAsState
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.BarChart
import androidx.compose.material.icons.filled.Book
import androidx.compose.material.icons.filled.CardGiftcard
import androidx.compose.material.icons.filled.Checklist
import androidx.compose.material.icons.filled.FavoriteBorder
import androidx.compose.material.icons.filled.Home
import androidx.compose.material.icons.filled.Notifications
import androidx.compose.material.icons.filled.Pets
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.NavigationBar
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.navigation.NavHostController
import androidx.navigation.NavType
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.compose.currentBackStackEntryAsState
import androidx.navigation.compose.rememberNavController
import androidx.navigation.navArgument
import com.example.mobile.presentation.ui.feedback.MicroFeedbackManager
import com.example.mobile.presentation.ui.screens.AchievementScreen
import com.example.mobile.presentation.ui.screens.ActivityTimelineScreen
import com.example.mobile.presentation.ui.screens.HabitCreationScreen
import com.example.mobile.presentation.ui.screens.HabitDetailScreen
import com.example.mobile.presentation.ui.screens.HabitEditScreen
import com.example.mobile.presentation.ui.screens.HabitsScreen
import com.example.mobile.presentation.ui.screens.HomeScreen
import com.example.mobile.presentation.ui.screens.NotificationSettingsScreen
import com.example.mobile.presentation.ui.screens.PetScreen
import com.example.mobile.presentation.ui.screens.RewardsScreen
import com.example.mobile.presentation.ui.screens.StatisticsScreen
import com.example.mobile.presentation.viewmodel.AchievementViewModel
import com.example.mobile.ui.theme.HabitPetTheme

@Composable
fun HabitPetNavGraph(
    navController: NavHostController = rememberNavController(),
    microFeedbackManager: MicroFeedbackManager? = null
) {
    HabitPetTheme {
        val backStackEntry by navController.currentBackStackEntryAsState()
        val currentRoute = backStackEntry?.destination?.route
        val achievementViewModel: AchievementViewModel = hiltViewModel()
        val claimableAchievementCount by achievementViewModel.claimableAchievementCount.collectAsState()

        Scaffold(
            bottomBar = {
                HabitPetBottomBar(
                    currentRoute = currentRoute,
                    claimableAchievementCount = claimableAchievementCount,
                    onNavigate = { route ->
                        navigateToBottomDestination(navController, route, microFeedbackManager)
                    }
                )
            }
        ) { innerPadding ->
            NavHost(
                navController = navController,
                startDestination = "home",
                modifier = Modifier
                    .fillMaxSize()
                    // Fixed: Apply ONLY the bottom padding generated by your custom NavigationBar component shell,
                    // letting top bars natively flush straight up with no structural margins.
                    .padding(bottom = innerPadding.calculateBottomPadding())
            ) {
                composable("home") {
                    HomeScreen(
                        onNavigateToHabits = { navigateToBottomDestination(navController, "habits", microFeedbackManager) },
                        onNavigateToHabitDetail = { habitId -> navController.navigate("habitDetail/$habitId") }
                    )
                }
                composable("habits") { HabitsScreen(navController = navController) }
                composable("habitCreation") {
                    HabitCreationScreen(
                        onNavigateUp = { navController.popBackStack() },
                        onHabitCreated = { navController.popBackStack() }
                    )
                }
                composable(
                    route = "habitEdit/{habitId}",
                    arguments = listOf(navArgument("habitId") { type = NavType.LongType })
                ) {
                    val habitId = it.arguments?.getLong("habitId") ?: 0L
                    HabitEditScreen(
                        habitId = habitId,
                        onNavigateUp = { navController.popBackStack() },
                        onHabitUpdated = { navController.popBackStack() },
                        onHabitDeleted = { navController.popBackStack() }
                    )
                }
                composable(
                    route = "habitDetail/{habitId}",
                    arguments = listOf(navArgument("habitId") { type = NavType.LongType })
                ) {
                    val habitId = it.arguments?.getLong("habitId") ?: 0L
                    HabitDetailScreen(
                        habitId = habitId,
                        onNavigateUp = { navController.popBackStack() }
                    )
                }
                composable("pet") { PetScreen() }
                composable("collection") { RewardsScreen() }
                composable("statistics") { StatisticsScreen() }
                composable("achievements") { AchievementScreen() }
                composable("activity") { ActivityTimelineScreen() }
                composable("notification_settings") { NotificationSettingsScreen() }
            }
        }
    }
}

private fun navigateToBottomDestination(
    navController: NavHostController,
    route: String,
    microFeedbackManager: MicroFeedbackManager?
) {
    microFeedbackManager?.triggerTabSwitched()
    navController.navigate(route) {
        popUpTo(navController.graph.startDestinationId) {
            inclusive = false
            saveState = true
        }
        launchSingleTop = true
        restoreState = false
    }
}

private data class BottomDestination(
    val route: String,
    val label: String,
    val icon: ImageVector,
    val badgeCount: Int = 0
)

@Composable
private fun HabitPetBottomBar(
    currentRoute: String?,
    claimableAchievementCount: Int,
    onNavigate: (String) -> Unit
) {
    val destinations = listOf(
        BottomDestination("home", "Home", Icons.Default.Home),
        BottomDestination("habits", "Habits", Icons.Default.Checklist),
        BottomDestination("pet", "Pet", Icons.Default.Pets),
        BottomDestination("collection", "Collection", Icons.Default.CardGiftcard),
        BottomDestination("statistics", "Stats", Icons.Default.BarChart),
        BottomDestination(
            route = "achievements",
            label = "Achievements",
            icon = Icons.Default.FavoriteBorder,
            badgeCount = claimableAchievementCount
        ),
        BottomDestination("activity", "Activity", Icons.Default.Book),
        BottomDestination("notification_settings", "Notifications", Icons.Default.Notifications)
    )

    NavigationBar(
        containerColor = Color(0xFFFFFFFF), // Matching modern minimalist background look
        tonalElevation = 0.dp
    ) {
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceEvenly
        ) {
            destinations.forEach { destination ->
                HabitPetBottomNavItem(
                    destination = destination,
                    selected = currentRoute == destination.route,
                    modifier = Modifier.weight(1f),
                    onNavigate = { onNavigate(destination.route) }
                )
            }
        }
    }
}

private val NavSelected = Color(0xFF8A76F9)
private val NavUnselected = Color(0xFF6F6A8A)
private val NavIndicator = Color(0xFFEDE7FF)

@Composable
private fun HabitPetBottomNavItem(
    destination: BottomDestination,
    selected: Boolean,
    modifier: Modifier = Modifier,
    onNavigate: () -> Unit
) {
    val indicatorWidth by animateDpAsState(if (selected) 58.dp else 48.dp)

    Box(
        modifier = modifier
            .height(64.dp)
            .clickable(onClick = onNavigate),
        contentAlignment = Alignment.Center
    ) {
        Box(
            modifier = Modifier
                .width(indicatorWidth)
                .height(40.dp)
                .background(
                    if (selected) NavIndicator else Color.Transparent,
                    RoundedCornerShape(20.dp)
                ),
            contentAlignment = Alignment.Center
        ) {
            Column(
                horizontalAlignment = Alignment.CenterHorizontally,
                verticalArrangement = Arrangement.spacedBy(3.dp)
            ) {
                BottomBarIcon(destination)
                Text(
                    text = destination.label,
                    style = MaterialTheme.typography.labelSmall,
                    color = if (selected) NavSelected else NavUnselected
                )
            }
        }
    }
}

@Composable
private fun BottomBarIcon(destination: BottomDestination) {
    val isAchievementBadgeVisible = destination.route == "achievements" && destination.badgeCount > 0
    val contentDescription = if (isAchievementBadgeVisible) {
        "${destination.label}, ${destination.badgeCount} achievements ready to claim"
    } else {
        destination.label
    }

    if (isAchievementBadgeVisible) {
        Box(contentAlignment = Alignment.CenterEnd) {
            Icon(
                imageVector = destination.icon,
                contentDescription = contentDescription,
                modifier = Modifier.padding(end = 8.dp)
            )
            Box(
                modifier = Modifier
                    .align(Alignment.TopEnd)
                    .size(16.dp) // Adjusted slightly smaller for visual elegance
                    .background(Color(0xFF22C55E), CircleShape),
                contentAlignment = Alignment.Center
            ) {
                Text(
                    text = destination.badgeCount.toString(),
                    color = Color.White,
                    style = MaterialTheme.typography.labelSmall.copy(fontSize = 9.sp, fontWeight = FontWeight.Bold)
                )
            }
        }
    } else {
        Icon(
            imageVector = destination.icon,
            contentDescription = contentDescription
        )
    }
}